import type { PagePlan } from '../types/pagePlan';
import type { GeneratedPageCta } from '../types/generatedPage';
import type { LayoutPattern } from '../types/referenceAnalysis';
import { deriveCta } from './cta';
import { generateReconstructionArtifact } from './reconstructionCodegen';

type LayoutKey = 'single-hero' | 'hero-cards' | 'dashboard-grid' | 'finder-flow';

interface LayoutVariant {
  /** The markup inside <main>, after the shared hero header. */
  sectionsMarkup: string;
  /** Variant-specific scoped-style rules appended after the shared base. */
  styles: string;
}

const LAYOUT_KEYS: Record<LayoutPattern, LayoutKey> = {
  'Single hero': 'single-hero',
  'Hero plus feature cards': 'hero-cards',
  'Dashboard grid': 'dashboard-grid',
  'Product finder flow': 'finder-flow',
};

/**
 * Turns a constrained page plan into a real, standalone Vue 3 SFC string —
 * `<script setup lang="ts">` + `<template>` + `<style scoped>`. This is the
 * "one-shot Vue output" step: unlike the HTML-string export, the result is an
 * actual component a developer can drop into a Vue project and edit.
 *
 * The component's *shape* is chosen from the analyzer's observed
 * `layoutPattern` (single hero, feature cards, dashboard grid, or finder
 * flow) — so a dashboard reference yields a grid of tiles and a product-finder
 * reference yields a row of option cards, not one fixed layout. Across every
 * variant the script block, the single `<h1>`, and the `v-for` over typed
 * `sections` rendering each as an `<h2>` stay invariant.
 *
 * Pure and deterministic (no DOM), so it is unit-testable and produces the
 * same SFC for the same plan. Page content lives in typed `const`s in the
 * script block and is rendered via `{{ }}` interpolation — so Vue handles HTML
 * escaping at runtime and this generator only needs to emit safe TS string
 * literals (see `jsString`). That keeps generated content injection-safe by
 * construction.
 */
export function generateVueSfc(plan: PagePlan): string {
  if (plan.reference.reconstruction) {
    return generateReconstructedVueSfc(plan);
  }

  const layoutKey = LAYOUT_KEYS[plan.reference.analysis.layoutPattern] ?? 'hero-cards';
  const variant = buildLayoutVariant(layoutKey);
  const cta = deriveCta(plan.reference.analysis.ctaStyle);
  const ctaMarkup = buildCtaMarkup(cta);
  const isFinder = layoutKey === 'finder-flow';
  const firstSectionTitle = plan.sections[0]?.title ?? '';

  const sectionsLiteral = plan.sections
    .map((section) => `  { title: ${jsString(section.title)}, body: ${jsString(section.body)} },`)
    .join('\n');

  const paletteStyles = buildPaletteStyleVars(plan.tokens.palette);

  return `<script setup lang="ts">
${isFinder ? "import { ref } from 'vue';\n" : ''}// Generated by the figma-to-vue pipeline from a constrained page plan
// (schema ${plan.schemaVersion}, layout "${plan.reference.analysis.layoutPattern}").
// This is a starting point, not a locked artifact — edit freely.
interface PageSection {
  title: string;
  body: string;
}

const kicker = ${jsString(plan.page.kicker)};
const title = ${jsString(plan.page.title)};
const summary = ${jsString(plan.page.summary)};

const sections: PageSection[] = [
${sectionsLiteral}
];
${isFinder ? `\nconst finderChoice = ref(${jsString(firstSectionTitle)});\n` : ''}</script>

<template>
  <main class="generated-page generated-page--${layoutKey}">
    <header class="generated-page__hero">
      <p class="generated-page__kicker">{{ kicker }}</p>
      <h1>{{ title }}</h1>
      <p class="generated-page__summary">{{ summary }}</p>
${ctaMarkup}${isFinder ? FINDER_MARKUP : ''}    </header>

${variant.sectionsMarkup}
  </main>
</template>

<style scoped>
.generated-page {
${paletteStyles}  display: grid;
  gap: 2rem;
  max-width: 70rem;
  margin: 0 auto;
  padding: 2rem;
  font-family: system-ui, sans-serif;
}

.generated-page__hero {
  padding: 2.5rem;
  border-radius: 12px;
  background: var(--token-surface-soft, #f4f6fb);
}

.generated-page__kicker {
  margin: 0 0 0.5rem;
  color: var(--token-accent, #4a90e2);
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  font-size: 0.85rem;
}

.generated-page__hero h1 {
  margin: 0 0 0.75rem;
  font-size: clamp(2rem, 5vw, 3.5rem);
  line-height: 1.05;
}

.generated-page__summary {
  margin: 0;
  max-width: 38rem;
  line-height: 1.6;
}
${cta.kind === 'none' && !isFinder ? '' : CTA_STYLES}${isFinder ? FINDER_STYLES : ''}${variant.styles}</style>
`;
}

function generateReconstructedVueSfc(plan: PagePlan): string {
  const reconstruction = plan.reference.reconstruction!;
  const artifact = generateReconstructionArtifact(reconstruction);
  return `<script setup lang="ts">
// Generated from ${reconstruction.source.kind} evidence using reconstruction-plan v2.
// Static source-dependent markup is intentionally editable after export.
</script>

<template>
${artifact.markup}
</template>

<style scoped>
${artifact.css}
</style>
`;
}

const FINDER_MARKUP = `      <form class="generated-page__finder" @submit.prevent>
        <label for="finder-choice">What are you looking for?</label>
        <div class="generated-page__finder-row">
          <select id="finder-choice" v-model="finderChoice">
            <option v-for="option in sections" :key="option.title" :value="option.title">{{ option.title }}</option>
          </select>
          <button type="submit" class="generated-page__cta">Show results</button>
        </div>
      </form>
`;

const FINDER_STYLES = `
.generated-page__finder {
  margin-top: 1.5rem;
  display: grid;
  gap: 0.5rem;
  max-width: 26rem;
}

.generated-page__finder > label {
  font-weight: 600;
  font-size: 0.85rem;
}

.generated-page__finder-row {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.generated-page__finder select {
  flex: 1 1 12rem;
  min-height: 44px;
  padding: 0 0.75rem;
  border: 1px solid #e4e7ee;
  border-radius: 8px;
  font: inherit;
}

.generated-page__finder .generated-page__cta {
  margin-top: 0;
}
`;

const CTA_STYLES = `
.generated-page__cta {
  display: inline-flex;
  align-items: center;
  min-height: 44px;
  margin-top: 1.5rem;
  padding: 0 1.25rem;
  border: none;
  border-radius: 8px;
  background: var(--token-accent, #4a90e2);
  color: #ffffff;
  font: inherit;
  font-weight: 700;
  cursor: pointer;
  text-decoration: none;
}

.generated-page__cta--link {
  min-height: 0;
  padding: 0;
  background: none;
  color: var(--token-accent, #4a90e2);
}

.generated-page__cta-form {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-top: 1.5rem;
}

.generated-page__cta-form input {
  min-height: 44px;
  padding: 0 0.75rem;
  border: 1px solid #e4e7ee;
  border-radius: 8px;
  font: inherit;
}

.generated-page__cta-form .generated-page__cta {
  margin-top: 0;
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
`;

/**
 * Emits the hero call-to-action markup for the generated SFC, matching the
 * live preview (GeneratedPagePreview.vue). Labels come from deriveCta and are
 * fixed strings, so no escaping is required. Indented to sit inside the hero.
 */
function buildCtaMarkup(cta: GeneratedPageCta): string {
  switch (cta.kind) {
    case 'button':
      return `      <button type="button" class="generated-page__cta">${cta.label}</button>\n`;
    case 'link':
      return `      <a class="generated-page__cta generated-page__cta--link" href="#">${cta.label} →</a>\n`;
    case 'form':
      return `      <form class="generated-page__cta-form" @submit.prevent>
        <label class="visually-hidden" for="generated-page-email">Email address</label>
        <input id="generated-page-email" type="email" placeholder="you@example.com" />
        <button type="submit" class="generated-page__cta">${cta.label}</button>
      </form>\n`;
    case 'none':
    default:
      return '';
  }
}

/**
 * Returns the section markup and the variant-specific scoped styles for a
 * layout. Every variant keeps the same `v-for` over `sections` rendering each
 * as `<h2>` + body, so only the container shape and styling differ.
 */
function buildLayoutVariant(layoutKey: LayoutKey): LayoutVariant {
  const sectionItems = `      <article v-for="section in sections" :key="section.title">
        <h2>{{ section.title }}</h2>
        <p>{{ section.body }}</p>
      </article>`;

  switch (layoutKey) {
    case 'single-hero':
      return {
        sectionsMarkup: `    <section class="generated-page__detail" aria-label="Page sections">
${sectionItems}
    </section>`,
        styles: `
.generated-page__detail {
  display: grid;
  gap: 1.5rem;
  max-width: 44rem;
}

.generated-page__detail h2 {
  margin: 0 0 0.4rem;
  font-size: 1.25rem;
}

.generated-page__detail p {
  margin: 0;
  line-height: 1.6;
}
`,
      };

    case 'dashboard-grid':
      return {
        sectionsMarkup: `    <section class="generated-page__grid" aria-label="Page sections">
${sectionItems}
    </section>`,
        styles: `
.generated-page__grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr));
  gap: 0.75rem;
}

.generated-page__grid article {
  padding: 1rem;
  border: 1px solid #e4e7ee;
  border-radius: 8px;
  background: #fff;
}

.generated-page__grid h2 {
  margin: 0 0 0.35rem;
  font-size: 0.95rem;
}

.generated-page__grid p {
  margin: 0;
  font-size: 0.85rem;
  line-height: 1.45;
}
`,
      };

    case 'finder-flow':
      return {
        sectionsMarkup: `    <section class="generated-page__options" aria-label="Page sections">
${sectionItems}
    </section>`,
        styles: `
.generated-page--finder-flow .generated-page__hero {
  text-align: center;
}

.generated-page__options {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 1.5rem;
}

.generated-page__options article {
  flex: 1 1 14rem;
  max-width: 16rem;
  padding: 1.5rem;
  border: 1px solid #e4e7ee;
  border-radius: 12px;
  text-align: center;
}

.generated-page__options h2 {
  margin: 0 0 0.5rem;
  font-size: 1.1rem;
}

.generated-page__options p {
  margin: 0;
  line-height: 1.5;
}
`,
      };

    case 'hero-cards':
    default:
      return {
        sectionsMarkup: `    <section class="generated-page__sections" aria-label="Page sections">
${sectionItems}
    </section>`,
        styles: `
.generated-page__sections {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(15rem, 1fr));
  gap: 1rem;
}

.generated-page__sections article {
  padding: 1.25rem;
  border: 1px solid #e4e7ee;
  border-radius: 10px;
}

.generated-page__sections h2 {
  margin: 0 0 0.5rem;
  font-size: 1.1rem;
}

.generated-page__sections p {
  margin: 0;
  line-height: 1.5;
}
`,
      };
  }
}

/**
 * Emits the scoped-style custom-property declarations for the extracted
 * palette, or an empty string when no palette was extracted (so the SFC falls
 * back to its hardcoded default colors). Returned with trailing newline +
 * indentation so it slots into the `.generated-page {` block.
 */
function buildPaletteStyleVars(palette: string[]): string {
  if (palette.length === 0) {
    return '';
  }

  const accent = palette[0];
  const surfaceSoft = palette[1] ?? palette[0];
  return `  --token-accent: ${accent};\n  --token-surface-soft: ${surfaceSoft};\n`;
}

/**
 * Produces a safe single-quoted TypeScript string literal for arbitrary text.
 * Escapes backslashes, single quotes, and newlines so generated content can
 * never break out of the literal.
 */
function jsString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '');
  return `'${escaped}'`;
}
