import type { PagePlan } from '../types/pagePlan';

/**
 * Turns a constrained page plan into a real, standalone Vue 3 SFC string —
 * `<script setup lang="ts">` + `<template>` + `<style scoped>`. This is the
 * "one-shot Vue output" step: unlike the HTML-string export, the result is an
 * actual component a developer can drop into a Vue project and edit.
 *
 * Pure and deterministic (no DOM), so it is unit-testable and produces the
 * same SFC for the same plan. Page content lives in typed `const`s in the
 * script block and is rendered via `{{ }}` interpolation — so Vue handles HTML
 * escaping at runtime and this generator only needs to emit safe TS string
 * literals (see `jsString`). That keeps generated content injection-safe by
 * construction.
 */
export function generateVueSfc(plan: PagePlan): string {
  const sectionsLiteral = plan.sections
    .map((section) => `  { title: ${jsString(section.title)}, body: ${jsString(section.body)} },`)
    .join('\n');

  const paletteStyles = buildPaletteStyleVars(plan.tokens.palette);

  return `<script setup lang="ts">
// Generated by the figma-to-vue pipeline from a constrained page plan
// (schema ${plan.schemaVersion}). This is a starting point, not a locked
// artifact — edit freely.
interface PageSection {
  title: string;
  body: string;
}

const kicker = ${jsString(plan.page.kicker)};
const title = ${jsString(plan.page.title)};
const summary = ${jsString(plan.page.summary)};

const sections: PageSection[] = [
${sectionsLiteral}
];
</script>

<template>
  <main class="generated-page">
    <header class="generated-page__hero">
      <p class="generated-page__kicker">{{ kicker }}</p>
      <h1>{{ title }}</h1>
      <p class="generated-page__summary">{{ summary }}</p>
    </header>

    <section class="generated-page__sections" aria-label="Page sections">
      <article v-for="section in sections" :key="section.title">
        <h2>{{ section.title }}</h2>
        <p>{{ section.body }}</p>
      </article>
    </section>
  </main>
</template>

<style scoped>
.generated-page {
${paletteStyles}  display: grid;
  gap: 2rem;
  max-width: 70rem;
  margin: 0 auto;
  padding: 2rem;
  font-family: system-ui, sans-serif;
}

.generated-page__hero {
  padding: 2.5rem;
  border-radius: 12px;
  background: var(--token-surface-soft, #f4f6fb);
}

.generated-page__kicker {
  margin: 0 0 0.5rem;
  color: var(--token-accent, #4a90e2);
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  font-size: 0.85rem;
}

.generated-page__hero h1 {
  margin: 0 0 0.75rem;
  font-size: clamp(2rem, 5vw, 3.5rem);
  line-height: 1.05;
}

.generated-page__summary {
  margin: 0;
  max-width: 38rem;
  line-height: 1.6;
}

.generated-page__sections {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(15rem, 1fr));
  gap: 1rem;
}

.generated-page__sections article {
  padding: 1.25rem;
  border: 1px solid #e4e7ee;
  border-radius: 10px;
}

.generated-page__sections h2 {
  margin: 0 0 0.5rem;
  font-size: 1.1rem;
}

.generated-page__sections p {
  margin: 0;
  line-height: 1.5;
}
</style>
`;
}

/**
 * Emits the scoped-style custom-property declarations for the extracted
 * palette, or an empty string when no palette was extracted (so the SFC falls
 * back to its hardcoded default colors). Returned with trailing newline +
 * indentation so it slots into the `.generated-page {` block.
 */
function buildPaletteStyleVars(palette: string[]): string {
  if (palette.length === 0) {
    return '';
  }

  const accent = palette[0];
  const surfaceSoft = palette[1] ?? palette[0];
  return `  --token-accent: ${accent};\n  --token-surface-soft: ${surfaceSoft};\n`;
}

/**
 * Produces a safe single-quoted TypeScript string literal for arbitrary text.
 * Escapes backslashes, single quotes, and newlines so generated content can
 * never break out of the literal.
 */
function jsString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '');
  return `'${escaped}'`;
}
